apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mapr-sqlserver-data01-student4 
  namespace: mapr-student4
spec:
  storageClassName: mapr-student4-sc 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100G
